---
title: "P8105_HW5_yz4188"
author: "Yueran Zhang"
date: "11/18/2021"
output: github_document
---

```{r setup,inclde = FALSE}
library(tidyverse)
library(patchwork)

```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


#Problem 1
```{r}
homicide_df = 
  read_csv('homicide-data.csv', na = c("", 'Unknown')) %>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved",
    )) %>% 
  
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```

About Baltimore, MD.

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution ==  "unsolved"),
    n = n()
)

baltimore_test = 
prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n))

baltimore_test %>%
  broom::tidy()
```

Iterate across cities.

```{r}
  prop_test_function = function(city_df){
    
    city_summary = 
      city_df %>% 
      summarize(
        unsolved = sum(resolution ==  "unsolved"),
        n = n()
)

    city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n))
    
    return(city_test)
  }

prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
prop_test_function()

```

Iterate all cities!
```{r}
results_df =
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data,prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state,tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate,starts_with("conf"))

```

Plot with estimates and CI.

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state,estimate)) %>% 
  ggplot(aes(x = city_state,y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

```{r}
homicide_df %>%
  group_by(city_state) %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    total = n()
  ) %>%
  mutate(
    test_results = map2(unsolved,total,prop.test),
    tidy_results = map(test_results,broom::tidy)
  ) %>% 
  select(city_state,tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate,starts_with("conf"))
```


## Problem 2 


```{r}
files = list.files("HW5-data",full.names = TRUE)
path_df = 
  tibble(map(files,read.csv)) %>%
  janitor::clean_names() %>%
  unnest() %>%
  mutate(path = files) %>%
  separate(path, into = c("dir","file_name"), sep = "/") %>%
  separate(file_name, into = c("control_arm","subject_id"), sep = "_") %>%
  separate(subject_id, into = c("subject_id","postfix"), sep = ".csv") %>%
  select(-dir,-postfix) %>% 
pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "value") %>% 

ggplot(aes(x = week, y = value, color = subject_id, group = subject_id)) +
  labs(title = " observations over time") + geom_line(alpha = 0.5) +
  facet_grid(. ~ control_arm) 

path_df

```
From the plot，we know that as the time increases, there is no significant difference of between the increasing observed value for the experiment arm and the control arm.


## Problem 3

```{r }
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


```{r}
missing_value = function(x){
  if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))
  }else if (is.character(x)){
    x = replace_na(x, "virginica")
  }
}

Full_Data = map(iris_with_missing,missing_value) %>% 
as_tibble()

Full_Data
```

